export const countryOptions = [
        { value: 'us', label: 'United States', flag: '🇺🇸' },
        { value: 'ca', label: 'Canada', flag: '🇨🇦' },
        { value: 'gb', label: 'United Kingdom', flag: '🇬🇧' },
        { value: 'au', label: 'Australia', flag: '🇦🇺' },
        { value: 'de', label: 'Germany', flag: '🇩🇪' },
        { value: 'fr', label: 'France', flag: '🇫🇷' },
        { value: 'it', label: 'Italy', flag: '🇮🇹' },
        { value: 'es', label: 'Spain', flag: '🇪🇸' },
        { value: 'jp', label: 'Japan', flag: '🇯🇵' },
        { value: 'cn', label: 'China', flag: '🇨🇳' },
        { value: 'kr', label: 'South Korea', flag: '🇰🇷' },
        { value: 'in', label: 'India', flag: '🇮🇳' },
        { value: 'pk', label: 'Pakistan', flag: '🇵🇰' },
        { value: 'ph', label: 'Philippines', flag: '🇵🇭' },
        { value: 'tw', label: 'Taiwan', flag: '🇹🇼' },
        { value: 'br', label: 'Brazil', flag: '🇧🇷' },
        { value: 'za', label: 'South Africa', flag: '🇿🇦' },
        { value: 'mx', label: 'Mexico', flag: '🇲🇽' },
        { value: 'ar', label: 'Argentina', flag: '🇦🇷' },
        { value: 'cl', label: 'Chile', flag: '🇨🇱' },
        { value: 'co', label: 'Colombia', flag: '🇨🇴' },
        { value: 'pe', label: 'Peru', flag: '🇵🇪' },
        { value: 'eg', label: 'Egypt', flag: '🇪🇬' },
        { value: 'ng', label: 'Nigeria', flag: '🇳🇬' },
        { value: 'sa', label: 'Saudi Arabia', flag: '🇸🇦' },
        { value: 'ae', label: 'United Arab Emirates', flag: '🇦🇪' },
        { value: 'tr', label: 'Turkey', flag: '🇹🇷' },
        { value: 'ru', label: 'Russia', flag: '🇷🇺' },
        { value: 'se', label: 'Sweden', flag: '🇸🇪' },
        { value: 'no', label: 'Norway', flag: '🇳🇴' },
        { value: 'dk', label: 'Denmark', flag: '🇩🇰' },
        { value: 'fi', label: 'Finland', flag: '🇫🇮' },
        { value: 'nl', label: 'Netherlands', flag: '🇳🇱' },
        { value: 'be', label: 'Belgium', flag: '🇧🇪' },
        { value: 'ch', label: 'Switzerland', flag: '🇨🇭' },
        { value: 'at', label: 'Austria', flag: '🇦🇹' },
        { value: 'pl', label: 'Poland', flag: '🇵🇱' },
        { value: 'cz', label: 'Czech Republic', flag: '🇨🇿' },
        { value: 'sk', label: 'Slovakia', flag: '🇸🇰' },
        { value: 'hu', label: 'Hungary', flag: '🇭🇺' },
        { value: 'ro', label: 'Romania', flag: '🇷🇴' },
        { value: 'bg', label: 'Bulgaria', flag: '🇧🇬' },
        { value: 'lt', label: 'Lithuania', flag: '🇱🇹' },
        { value: 'lv', label: 'Latvia', flag: '🇱🇻' },
        { value: 'ee', label: 'Estonia', flag: '🇪🇪' },
        { value: 'by', label: 'Belarus', flag: '🇧🇾' },
        { value: 'ua', label: 'Ukraine', flag: '🇺🇦' },
        { value: 'md', label: 'Moldova', flag: '🇲🇩' },
        { value: 'gr', label: 'Greece', flag: '🇬🇷' },
        { value: 'pt', label: 'Portugal', flag: '🇵🇹' },
        { value: 'ie', label: 'Ireland', flag: '🇮🇪' },
        { value: 'is', label: 'Iceland', flag: '🇮🇸' },
        { value: 'mt', label: 'Malta', flag: '🇲🇹' },
        { value: 'cy', label: 'Cyprus', flag: '🇨🇾' },
        { value: 'my', label: 'Malaysia', flag: '🇲🇾' },
        { value: 'sg', label: 'Singapore', flag: '🇸🇬' },
        { value: 'th', label: 'Thailand', flag: '🇹🇭' },
        { value: 'vn', label: 'Vietnam', flag: '🇻🇳' },
        { value: 'id', label: 'Indonesia', flag: '🇮🇩' },
        { value: 'nz', label: 'New Zealand', flag: '🇳🇿' },
        { value: 'ir', label: 'Iran', flag: '🇮🇷' },
        { value: 'iq', label: 'Iraq', flag: '🇮🇶' },
        { value: 'sy', label: 'Syria', flag: '🇸🇾' },
        { value: 'il', label: 'Israel', flag: '🇮🇱' },
        { value: 'jo', label: 'Jordan', flag: '🇯🇴' },
        { value: 'lb', label: 'Lebanon', flag: '🇱🇧' },
        { value: 'ma', label: 'Morocco', flag: '🇲🇦' },
        { value: 'tn', label: 'Tunisia', flag: '🇹🇳' },
        { value: 'dz', label: 'Algeria', flag: '🇩🇿' },
        { value: 'ke', label: 'Kenya', flag: '🇰🇪' },
        { value: 'gh', label: 'Ghana', flag: '🇬🇭' },
        { value: 'et', label: 'Ethiopia', flag: '🇪🇹' },
        { value: 'ug', label: 'Uganda', flag: '🇺🇬' },
        { value: 'zm', label: 'Zambia', flag: '🇿🇲' },
        { value: 'zw', label: 'Zimbabwe', flag: '🇿🇼' },
        { value: 'mg', label: 'Madagascar', flag: '🇲🇬' },
        { value: 'mu', label: 'Mauritius', flag: '🇲🇺' },
        { value: 'lk', label: 'Sri Lanka', flag: '🇱🇰' },
        { value: 'np', label: 'Nepal', flag: '🇳🇵' },
        { value: 'bd', label: 'Bangladesh', flag: '🇧🇩' },
        { value: 'mm', label: 'Myanmar', flag: '🇲🇲' },
        { value: 'kh', label: 'Cambodia', flag: '🇰🇭' },
        { value: 'la', label: 'Laos', flag: '🇱🇦' },
        { value: 'mn', label: 'Mongolia', flag: '🇲🇳' },
        { value: 'bt', label: 'Bhutan', flag: '🇧🇹' },
        { value: 'af', label: 'Afghanistan', flag: '🇦🇫' },
        { value: 'ye', label: 'Yemen', flag: '🇾🇪' },
        { value: 'om', label: 'Oman', flag: '🇴🇲' },
        { value: 'qa', label: 'Qatar', flag: '🇶🇦' },
        { value: 'bh', label: 'Bahrain', flag: '🇧🇭' },
        { value: 'kw', label: 'Kuwait', flag: '🇰🇼' },
        { value: 'kz', label: 'Kazakhstan', flag: '🇰🇿' },
        { value: 'uz', label: 'Uzbekistan', flag: '🇺🇿' },
        { value: 'tj', label: 'Tajikistan', flag: '🇹🇯' },
        { value: 'tm', label: 'Turkmenistan', flag: '🇹🇲' },
        { value: 'kg', label: 'Kyrgyzstan', flag: '🇰🇬' },
        { value: 'az', label: 'Azerbaijan', flag: '🇦🇿' },
        { value: 'am', label: 'Armenia', flag: '🇦🇲' },    
];

export const skillLevelOptions = [
    { value: 'Xiangqi Newbie', label: '兵' },   
    { value: 'Beginner', label: '象' },        
    { value: 'Intermediate', label: '炮' },   
    { value: 'Advanced', label: '車' },       
];
